"""initial tables

Revision ID: da983e404398
Revises: 
Create Date: 2026-02-18 11:31:01.922575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da983e404398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Key 名称（用于标识）'),
    sa.Column('hashed_key', sa.String(length=64), nullable=False, comment='SHA-256 哈希后的 Key'),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='Key 前缀（用于显示，如 sk-abc1...）'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='绑定的分组 ID（为空表示使用默认分组）'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('token_quota', sa.BigInteger(), nullable=False, comment='Token 额度上限（0 表示无限制）'),
    sa.Column('tokens_used', sa.BigInteger(), nullable=False, comment='已消耗 Token 数'),
    sa.Column('request_count', sa.BigInteger(), nullable=False, comment='累计请求次数'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最近使用时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_hashed_key'), ['hashed_key'], unique=True)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True, comment='访问令牌'),
    sa.Column('refresh_token', sa.Text(), nullable=False, comment='刷新令牌'),
    sa.Column('profile_arn', sa.String(length=512), nullable=True, comment='Profile ARN'),
    sa.Column('expires_at', sa.String(length=64), nullable=True, comment='过期时间 (RFC3339)'),
    sa.Column('auth_method', sa.String(length=16), nullable=False, comment='认证方式: social / idc'),
    sa.Column('client_id', sa.String(length=256), nullable=True, comment='OIDC Client ID (IdC)'),
    sa.Column('client_secret', sa.String(length=256), nullable=True, comment='OIDC Client Secret (IdC)'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='所属分组 ID'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级（数字越小越高）'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='是否已禁用'),
    sa.Column('region', sa.String(length=32), nullable=True, comment='凭据级 Region'),
    sa.Column('auth_region', sa.String(length=32), nullable=True, comment='凭据级 Auth Region'),
    sa.Column('api_region', sa.String(length=32), nullable=True, comment='凭据级 API Region'),
    sa.Column('machine_id', sa.String(length=128), nullable=True, comment='凭据级 Machine ID'),
    sa.Column('email', sa.String(length=256), nullable=True, comment='用户邮箱'),
    sa.Column('subscription_title', sa.String(length=64), nullable=True, comment='订阅等级 (KIRO PRO+ / KIRO FREE)'),
    sa.Column('proxy_url', sa.String(length=512), nullable=True, comment="代理 URL（'direct' 表示不使用代理）"),
    sa.Column('proxy_username', sa.String(length=128), nullable=True, comment='代理用户名'),
    sa.Column('proxy_password', sa.String(length=128), nullable=True, comment='代理密码'),
    sa.Column('fail_count', sa.Integer(), nullable=False, comment='连续失败次数'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最近使用时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分组名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='分组描述'),
    sa.Column('load_balancing_mode', sa.String(length=16), nullable=True, comment='分组级负载均衡模式（为空时使用全局配置）: priority / balanced'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True, comment='关联的 API Key ID'),
    sa.Column('credential_id', sa.Integer(), nullable=True, comment='使用的凭据 ID'),
    sa.Column('model', sa.String(length=128), nullable=False, comment='请求的模型名称'),
    sa.Column('endpoint', sa.String(length=64), nullable=False, comment='请求的端点路径'),
    sa.Column('client_ip', sa.String(length=64), nullable=True, comment='客户端 IP'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='输入 Token 数'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='输出 Token 数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总 Token 数'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP 状态码'),
    sa.Column('error_message', sa.String(length=512), nullable=True, comment='错误信息（如有）'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='请求耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_api_key_id'))

    op.drop_table('usage_logs')
    op.drop_table('groups')
    op.drop_table('credentials')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_hashed_key'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
